name: push 6

on: [push, pull_request]

jobs:
  my_first_job:
    name: My first job
    if: github.event_name == 'push'
    print-event:
      runs-on: ubuntu-latest
      steps:
        - name: Print the event that triggered this workflow
          run: |
            echo ${{ github.event_name }}
        - name: Print the current time
          run: |
            echo $(date)
  my_second_job:
    name: My second job
    if: github.event_name == 'push' &&github.event_name == 'pull_request'
    print-event:
      runs-on: ubuntu-latest
      steps:
        - name: Print the event that triggered this workflow
          run: |
            echo ${{ github.event_name }}
        - name: Print the current time
          run: |
            echo $(date)