name: SCHEDULE 3

on: 
  push:
  schedule:
    - cron: '0 3 * * THU'

jobs:
  print-event:
    runs-on: ubuntu-latest

    steps:
      - name: Print the event that triggered this workflow
        run: |
          echo ${{ github.event_name }}
      - name: Print the current time
        run: |
          echo $(date)
          
jobs:
  print-event:
    runs-on: ubuntu-latest

    steps:
      - name: Print the event that triggered this workflow
        run: |
          echo ${{ github.event_name }}
      - name: Print the current time
        run: |
          echo $(date)